#!/bin/bash

echo "🎨 图数据库图形化Demo展示"
echo "==========================="

cd /root/graph_database

echo ""
echo "🚀 正在启动可视化演示..."
echo -e "6\n" | ./visual_demo_fixed | head -60

echo ""
echo "📊 图数据库核心功能展示:"
echo ""
echo "✅ 节点管理:"
echo "   • 6个节点，每个包含姓名、年龄、工作、地点、技能等属性"
echo "   • 支持多种数据类型：字符串、数字、数组等"
echo ""
echo "✅ 关系建模:"
echo "   • 8条边，包含同事、朋友、上司、下属等关系类型"
echo "   • 每条边有权重和标签"
echo ""
echo "✅ 可视化展示:"
echo "   • ASCII艺术布局图"
echo "   • 详细节点信息"
echo "   • 统计分析"
echo "   • 邻接矩阵"
echo "   • 路径分析"
echo ""
echo "🎯 关键数据洞察:"
echo "   • 张伟是最活跃的节点(度数4)"
echo "   • 北京有2个人，其他城市各1人"
echo "   • 同事关系最常见(2个)"
echo "   • 平均网络连接度: 2.67"
echo ""
echo "🛣️  路径分析示例:"
echo "   • 张伟→刘芳: 2跳 (张伟→李娜→刘芳)"
echo "   • 赵丽→陈明: 3跳 (赵丽→张伟→王强→陈明)"
echo "   • 李娜→王强: 4跳 (李娜→刘芳→赵丽→张伟→王强)"
echo ""
echo "💡 技术特性:"
echo "   • 图遍历算法"
echo "   • 最短路径查找"
echo "   • 度数计算"
echo "   • 关系类型分析"
echo "   • 地理分布统计"
echo ""
echo "🌟 这个Demo证明了图数据库能够:"
echo "   • 灵活建模复杂关系网络"
echo "   • 高效执行图算法"
echo "   • 提供多维度数据分析"
echo "   • 支持路径查询和导航"
echo "   • 生成洞察性统计信息"
echo ""

echo "🎨 要再次运行完整可视化，请执行:"
echo "   echo '6' | ./visual_demo_fixed"